services:
  apirest: 
    image: api-rest
    #build:
    # Construction options. This will build the image from the dockerfile.  
    # Context is where the files to build are. Dockerfile is where this file can be found.
    #  context: /home/elias/tbSectra/backend/sectraplugin_backend
    #  dockerfile: API REST/Dockerfile
    environment:
    # Environment are the variables that will be used in the container. Replaces the .env file for example.
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080
        - ASPNETCORE_HTTPS_PORTS=8081
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        - ASPNETCORE_Kestrel__Certificates__Default__Password=password #Change this pass here & dockerfile
    ports:
        - "8086:8080"
        - "8087:8081"
    volumes:
        - ${APPDATA}/Microsoft/UserSecrets:/home/appBackend/.microsoft/usersecrets:ro
        - ${APPDATA}/ASP.NET/Https:/home/appBackend/.aspnet/https:ro
        # folder to acces histopathological images
        - /home/elias/tbSectra/ai/data/tcga:/home/user/appBackend/data/tcga
        - /home/elias/tbSectra/ai/data/outputs:/home/user/appBackend/data/outputs 
        # Folder to acces the "docker-compose.yml" to restart the container histolung from inside the container api-rest
        - /home/elias/tbSectra/ai/histo_lung:/home/user/appBackend/histo_lung  
        # file acces to the .env file from the container to update it
        - /home/elias/tbSectra/ai/histo_lung/.env:/home/user/appBackend/.env:rw
        # Need this to execute docker inside the container
        - /var/run/docker.sock:/var/run/docker.sock
        
