services:
  apirest:
    image: ${DOCKER_REGISTRY-}apirest
    build:
    # Construction options. This will build the image from the dockerfile.  
    # Context is where the files to build are. Dockerfile is where this file can be found.
      context: .
      dockerfile: API REST/Dockerfile
    environment:
    # Environment are .env variables
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080
        - ASPNETCORE_HTTPS_PORTS=8081
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        - ASPNETCORE_Kestrel__Certificates__Default__Password=password #Change this pass here & dockerfile
    ports:
        - "8086:8080"
        - "8087:8081"
    volumes:
        - ${APPDATA}/Microsoft/UserSecrets:/home/appBackend/.microsoft/usersecrets:ro
        - ${APPDATA}/ASP.NET/Https:/home/appBackend/.aspnet/https:ro
        
